version: '3.5'

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    deploy:
      resources:
        limits:
          cpus: '0.13'
          memory: '140MB'